cursor #cbe3e7
cursor_text_color #8a889d

foreground            #cbe3e7
background            #100e23
selection_foreground  #100e23
selection_background  #ffe6b3
url_color             #abf8f7

color0   #1E1C31
color1   #ffa572
color2   #7cf886
color3   #fff472
color4   #93ebea
color5   #317271
color6   #ABF8F7
color7   #effffe
color8   #95a1a1
color9   #ffc19f
color10  #a5ffac
color11  #fff8a5
color12  #bbfffe
color13  #c7fffe
color14  #dbfffe
color15  #f8fffe
