local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, { desc = "Find Files (Telescope)" })
vim.keymap.set('n', '<leader>fs', builtin.grep_string, { desc = "Grep String Under Cursor" })
vim.keymap.set('n', '<leader>fr', builtin.oldfiles, { desc = "Open Recent Files" })
vim.keymap.set('n', '<leader>fg', builtin.live_grep, { desc = "Live Grep (Search Text)" })
vim.keymap.set('n', '<leader>fb', builtin.buffers, { desc = "List Open Buffers" })
vim.keymap.set('n', '<leader>fh', builtin.help_tags, { desc = "Search Help Tags" })
vim.keymap.set('n', '<C-n>', ':NvimTreeToggle <CR>', { desc = "Toggle File Explorer" })
vim.keymap.set('n', '<leader>fc', ':CopilotChat <CR>', {})
