require('config.lazy')
require('config.general')
require('config.lsp')
require('config.autopairs')
require('config.formatter')
require('config.telescope')
require('config.cord')
require('config.treesitter')
require('config.alpha')
require('render-markdown')
require('config.keymaps')
require('config.bufferline')
require('config.gitsigns')
require('config.lualine')
require('config.indent-blankline')
require('config.mason')
-- require('config.feline')

-- require('config.cmp')
-- require('config.nvim-tree'1f2329)
